/**
 * Autogenerated by Thrift for if/KeyValue.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */
#include "if/gen-cpp2/KeyValue_types_custom_protocol.h"

namespace kv {

template void PutRequest::readNoXfer<>(apache::thrift::BinaryProtocolReader*);
template uint32_t PutRequest::write<>(apache::thrift::BinaryProtocolWriter*) const;
template uint32_t PutRequest::serializedSize<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t PutRequest::serializedSizeZC<>(apache::thrift::BinaryProtocolWriter const*) const;

template void GetResponse::readNoXfer<>(apache::thrift::BinaryProtocolReader*);
template uint32_t GetResponse::write<>(apache::thrift::BinaryProtocolWriter*) const;
template uint32_t GetResponse::serializedSize<>(apache::thrift::BinaryProtocolWriter const*) const;
template uint32_t GetResponse::serializedSizeZC<>(apache::thrift::BinaryProtocolWriter const*) const;

} // namespace kv
