/**
 * Autogenerated by Thrift for if/KeyValue.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */
#include <thrift/lib/cpp2/gen/module_metadata_cpp.h>
#include "if/gen-cpp2/KeyValue_metadata.h"

// some of these functions can be so large that the compiler gives up optimizing
// them - and issues a warning which may be treated as an error!
//
// these functions are so rarely called that it is probably okay for them not to
// be optimized in practice
FOLLY_CLANG_DISABLE_WARNING("-Wignored-optimization-argument")

namespace apache {
namespace thrift {
namespace detail {
namespace md {
using ThriftMetadata = ::apache::thrift::metadata::ThriftMetadata;
using ThriftPrimitiveType = ::apache::thrift::metadata::ThriftPrimitiveType;
using ThriftType = ::apache::thrift::metadata::ThriftType;
using ThriftService = ::apache::thrift::metadata::ThriftService;
using ThriftServiceContext = ::apache::thrift::metadata::ThriftServiceContext;
using ThriftFunctionGenerator = void (*)(ThriftMetadata&, ThriftService&);


const ::apache::thrift::metadata::ThriftStruct&
StructMetadata<::kv::PutRequest>::gen(ThriftMetadata& metadata) {
  auto res = metadata.structs()->emplace("KeyValue.PutRequest", ::apache::thrift::metadata::ThriftStruct{});
  if (!res.second) {
    return res.first->second;
  }
  ::apache::thrift::metadata::ThriftStruct& KeyValue_PutRequest = res.first->second;
  KeyValue_PutRequest.name() = "KeyValue.PutRequest";
  KeyValue_PutRequest.is_union() = false;
  static const auto* const
  KeyValue_PutRequest_fields = new std::array<EncodedThriftField, 2>{ {
    { 1, "key", false, std::make_unique<Primitive>(ThriftPrimitiveType::THRIFT_STRING_TYPE), std::vector<ThriftConstStruct>{ }},    { 2, "value", false, std::make_unique<Primitive>(ThriftPrimitiveType::THRIFT_STRING_TYPE), std::vector<ThriftConstStruct>{ }},  }};
  for (const auto& f : *KeyValue_PutRequest_fields) {
    ::apache::thrift::metadata::ThriftField field;
    field.id() = f.id;
    field.name() = f.name;
    field.is_optional() = f.is_optional;
    f.metadata_type_interface->writeAndGenType(*field.type(), metadata);
    field.structured_annotations() = f.structured_annotations;
    KeyValue_PutRequest.fields()->push_back(std::move(field));
  }
  return res.first->second;
}
const ::apache::thrift::metadata::ThriftStruct&
StructMetadata<::kv::GetResponse>::gen(ThriftMetadata& metadata) {
  auto res = metadata.structs()->emplace("KeyValue.GetResponse", ::apache::thrift::metadata::ThriftStruct{});
  if (!res.second) {
    return res.first->second;
  }
  ::apache::thrift::metadata::ThriftStruct& KeyValue_GetResponse = res.first->second;
  KeyValue_GetResponse.name() = "KeyValue.GetResponse";
  KeyValue_GetResponse.is_union() = false;
  static const auto* const
  KeyValue_GetResponse_fields = new std::array<EncodedThriftField, 2>{ {
    { 1, "found", false, std::make_unique<Primitive>(ThriftPrimitiveType::THRIFT_BOOL_TYPE), std::vector<ThriftConstStruct>{ }},    { 2, "value", false, std::make_unique<Primitive>(ThriftPrimitiveType::THRIFT_STRING_TYPE), std::vector<ThriftConstStruct>{ }},  }};
  for (const auto& f : *KeyValue_GetResponse_fields) {
    ::apache::thrift::metadata::ThriftField field;
    field.id() = f.id;
    field.name() = f.name;
    field.is_optional() = f.is_optional;
    f.metadata_type_interface->writeAndGenType(*field.type(), metadata);
    field.structured_annotations() = f.structured_annotations;
    KeyValue_GetResponse.fields()->push_back(std::move(field));
  }
  return res.first->second;
}

void ServiceMetadata<::apache::thrift::ServiceHandler<::kv::KeyValueStore>>::gen_put([[maybe_unused]] ThriftMetadata& metadata, ThriftService& service) {
  ::apache::thrift::metadata::ThriftFunction func;
  func.name() = "put";
  auto func_ret_type = std::make_unique<Primitive>(ThriftPrimitiveType::THRIFT_VOID_TYPE);
  func_ret_type->writeAndGenType(*func.return_type(), metadata);
  ::apache::thrift::metadata::ThriftField KeyValue_KeyValueStore_put_req_1;
  KeyValue_KeyValueStore_put_req_1.id() = 1;
  KeyValue_KeyValueStore_put_req_1.name() = "req";
  KeyValue_KeyValueStore_put_req_1.is_optional() = false;
  auto KeyValue_KeyValueStore_put_req_1_type = std::make_unique<Struct<::kv::PutRequest>>("KeyValue.PutRequest");
  KeyValue_KeyValueStore_put_req_1_type->writeAndGenType(*KeyValue_KeyValueStore_put_req_1.type(), metadata);
  func.arguments()->push_back(std::move(KeyValue_KeyValueStore_put_req_1));
  func.is_oneway() = false;
  service.functions()->push_back(std::move(func));
}
void ServiceMetadata<::apache::thrift::ServiceHandler<::kv::KeyValueStore>>::gen_get([[maybe_unused]] ThriftMetadata& metadata, ThriftService& service) {
  ::apache::thrift::metadata::ThriftFunction func;
  func.name() = "get";
  auto func_ret_type = std::make_unique<Struct<::kv::GetResponse>>("KeyValue.GetResponse");
  func_ret_type->writeAndGenType(*func.return_type(), metadata);
  ::apache::thrift::metadata::ThriftField KeyValue_KeyValueStore_get_key_1;
  KeyValue_KeyValueStore_get_key_1.id() = 1;
  KeyValue_KeyValueStore_get_key_1.name() = "key";
  KeyValue_KeyValueStore_get_key_1.is_optional() = false;
  auto KeyValue_KeyValueStore_get_key_1_type = std::make_unique<Primitive>(ThriftPrimitiveType::THRIFT_STRING_TYPE);
  KeyValue_KeyValueStore_get_key_1_type->writeAndGenType(*KeyValue_KeyValueStore_get_key_1.type(), metadata);
  func.arguments()->push_back(std::move(KeyValue_KeyValueStore_get_key_1));
  func.is_oneway() = false;
  service.functions()->push_back(std::move(func));
}

void ServiceMetadata<::apache::thrift::ServiceHandler<::kv::KeyValueStore>>::gen(::apache::thrift::metadata::ThriftServiceMetadataResponse& response) {
  const ::apache::thrift::metadata::ThriftServiceContextRef* self = genRecurse(*response.metadata(), *response.services());
  DCHECK(self != nullptr);
  // TODO(praihan): Remove ThriftServiceContext from response. But in the meantime, we need to fill the field with the result of looking up in ThriftMetadata.
  ::apache::thrift::metadata::ThriftServiceContext context;
  context.module() = *self->module();
  context.service_info() = response.metadata()->services()->at(*self->service_name());
  response.context() = std::move(context);
}

const ThriftServiceContextRef* ServiceMetadata<::apache::thrift::ServiceHandler<::kv::KeyValueStore>>::genRecurse([[maybe_unused]] ThriftMetadata& metadata, std::vector<ThriftServiceContextRef>& services) {
  ::apache::thrift::metadata::ThriftService KeyValue_KeyValueStore;
  KeyValue_KeyValueStore.name() = "KeyValue.KeyValueStore";
  static const ThriftFunctionGenerator functions[] = {
    ServiceMetadata<::apache::thrift::ServiceHandler<::kv::KeyValueStore>>::gen_put,
    ServiceMetadata<::apache::thrift::ServiceHandler<::kv::KeyValueStore>>::gen_get,
  };
  for (auto& function_gen : functions) {
    function_gen(metadata, KeyValue_KeyValueStore);
  }
  // We need to keep the index around because a reference or iterator could be invalidated.
  auto selfIndex = services.size();
  services.emplace_back();
  ThriftServiceContextRef& context = services[selfIndex];
  metadata.services()->emplace("KeyValue.KeyValueStore", std::move(KeyValue_KeyValueStore));
  context.service_name() = "KeyValue.KeyValueStore";
  ::apache::thrift::metadata::ThriftModuleContext module;
  module.name() = "KeyValue";
  context.module() = std::move(module);
  return &context;
}
} // namespace md
} // namespace detail
} // namespace thrift
} // namespace apache
