/**
 * Autogenerated by Thrift for if/KeyValue.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */
#pragma once

#include <thrift/lib/cpp2/gen/module_constants_h.h>

#include "if/gen-cpp2/KeyValue_types.h"

namespace kv {
/** Glean {"file": "if/KeyValue.thrift"} */
namespace KeyValue_constants {

  FOLLY_EXPORT ::std::string_view _fbthrift_schema_576b3dc35ad691a2();
  FOLLY_EXPORT ::folly::Range<const ::std::string_view*> _fbthrift_schema_576b3dc35ad691a2_includes();
  FOLLY_EXPORT ::folly::Range<const ::std::string_view*> _fbthrift_schema_576b3dc35ad691a2_uris();

} // namespace KeyValue_constants
} // namespace kv
