/**
 * Autogenerated by Thrift for if/KeyValue.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */
#pragma once
#include "if/gen-cpp2/KeyValue_for_each_field.h"
#include "if/gen-cpp2/KeyValue_visit_union.h"
#include "if/gen-cpp2/KeyValue_visit_by_thrift_field_metadata.h"
