/**
 * Autogenerated by Thrift for if/KeyValue.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */
#pragma once

#include <thrift/lib/cpp2/gen/client_h.h>

#include "if/gen-cpp2/KeyValue_types.h"

namespace apache { namespace thrift {
  class Cpp2RequestContext;
  namespace detail { namespace ac { struct ClientRequestContext; }}
  namespace transport { class THeader; }
}}

namespace kv {
class KeyValueStore;
} // namespace kv
namespace apache::thrift {

namespace detail {

template<>
struct ServiceMethodTypesFootprint<::kv::KeyValueStore> {
  // The types that appear in the definitions of service methods.
  // e.g. if it appears as a type of an input, output, exception sink or stream
  // parameter of a client stub, it appears here,
  using TypesInMethods = folly::tag_t<
  ::kv::PutRequest,
  void,
  ::std::string,
  ::kv::GetResponse>;
};
} // namespace detail

template <>
class Client<::kv::KeyValueStore> : public apache::thrift::GeneratedAsyncClient {
  static_assert(!folly::is_detected_v<::apache::thrift::detail::st::detect_complete, ::kv::KeyValueStore>, "Definition collision with service tag. Either rename the Thrift service using @cpp.Name annotation or rename the conflicting C++ type.");
 public:
  using apache::thrift::GeneratedAsyncClient::GeneratedAsyncClient;

  std::string_view getServiceName() const noexcept override {
    return "KeyValueStore";
  }


  /** Glean {"file": "if/KeyValue.thrift", "service": "KeyValueStore", "function": "put"} */
  virtual void put(std::unique_ptr<apache::thrift::RequestCallback> callback, const ::kv::PutRequest& p_req);
  /** Glean {"file": "if/KeyValue.thrift", "service": "KeyValueStore", "function": "put"} */
  virtual void put(apache::thrift::RpcOptions& rpcOptions, std::unique_ptr<apache::thrift::RequestCallback> callback, const ::kv::PutRequest& p_req);
 protected:
  void fbthrift_serialize_and_send_put(apache::thrift::RpcOptions& rpcOptions, std::shared_ptr<apache::thrift::transport::THeader> header, apache::thrift::ContextStack* contextStack, apache::thrift::RequestClientCallback::Ptr callback, const ::kv::PutRequest& p_req, bool stealRpcOptions = false);
 public:

  /** Glean {"file": "if/KeyValue.thrift", "service": "KeyValueStore", "function": "put"} */
  virtual void sync_put(const ::kv::PutRequest& p_req);
  /** Glean {"file": "if/KeyValue.thrift", "service": "KeyValueStore", "function": "put"} */
  virtual void sync_put(apache::thrift::RpcOptions& rpcOptions, const ::kv::PutRequest& p_req);

  /** Glean {"file": "if/KeyValue.thrift", "service": "KeyValueStore", "function": "put"} */
  virtual folly::Future<folly::Unit> future_put(const ::kv::PutRequest& p_req);
  /** Glean {"file": "if/KeyValue.thrift", "service": "KeyValueStore", "function": "put"} */
  virtual folly::SemiFuture<folly::Unit> semifuture_put(const ::kv::PutRequest& p_req);
  /** Glean {"file": "if/KeyValue.thrift", "service": "KeyValueStore", "function": "put"} */
  virtual folly::Future<folly::Unit> future_put(apache::thrift::RpcOptions& rpcOptions, const ::kv::PutRequest& p_req);
  /** Glean {"file": "if/KeyValue.thrift", "service": "KeyValueStore", "function": "put"} */
  virtual folly::SemiFuture<folly::Unit> semifuture_put(apache::thrift::RpcOptions& rpcOptions, const ::kv::PutRequest& p_req);

#if FOLLY_HAS_COROUTINES
  /** Glean {"file": "if/KeyValue.thrift", "service": "KeyValueStore", "function": "put"} */
  template <int = 0>
  folly::coro::Task<void> co_put(const ::kv::PutRequest& p_req) {
    return co_put<false>(nullptr, p_req);
  }
  /** Glean {"file": "if/KeyValue.thrift", "service": "KeyValueStore", "function": "put"} */
  template <int = 0>
  folly::coro::Task<void> co_put(apache::thrift::RpcOptions& rpcOptions, const ::kv::PutRequest& p_req) {
    return co_put<true>(&rpcOptions, p_req);
  }
 private:
  template <bool hasRpcOptions>
  folly::coro::Task<void> co_put(apache::thrift::RpcOptions* rpcOptions, const ::kv::PutRequest& p_req) {
    const folly::CancellationToken& cancelToken =
        co_await folly::coro::co_current_cancellation_token;
    const bool cancellable = cancelToken.canBeCancelled();
    apache::thrift::ClientReceiveState returnState;
    apache::thrift::ClientCoroCallback<false> callback(&returnState, co_await folly::coro::co_current_executor);
    auto protocolId = apache::thrift::GeneratedAsyncClient::getChannel()->getProtocolId();
    auto [ctx, header] = putCtx(rpcOptions);
    using CancellableCallback = apache::thrift::CancellableRequestClientCallback<false>;
    auto cancellableCallback = cancellable ? CancellableCallback::create(&callback, channel_) : nullptr;
    static apache::thrift::RpcOptions* defaultRpcOptions = new apache::thrift::RpcOptions();
    auto wrappedCallback = apache::thrift::RequestClientCallback::Ptr(cancellableCallback ? (apache::thrift::RequestClientCallback*)cancellableCallback.get() : &callback);
    if (ctx != nullptr) {
      auto argsAsRefs = std::tie(p_req);
      auto interceptorTry = ctx->processClientInterceptorsOnRequest(apache::thrift::ClientInterceptorOnRequestArguments(argsAsRefs), header.get(), hasRpcOptions ? *rpcOptions : *defaultRpcOptions);
      if (interceptorTry.hasException()) {
        co_yield folly::coro::co_error(std::move(interceptorTry.exception()));
      }
    }
    if constexpr (hasRpcOptions) {
      fbthrift_serialize_and_send_put(*rpcOptions, header, ctx.get(), std::move(wrappedCallback), p_req);
    } else {
      fbthrift_serialize_and_send_put(*defaultRpcOptions, header, ctx.get(), std::move(wrappedCallback), p_req);
    }
    if (cancellable) {
      folly::CancellationCallback cb(cancelToken, [&] { CancellableCallback::cancel(std::move(cancellableCallback)); });
      co_await callback.co_waitUntilDone();
    } else {
      co_await callback.co_waitUntilDone();
    }
    if (returnState.isException()) {
      co_yield folly::coro::co_error(std::move(returnState.exception()));
    }
    returnState.resetProtocolId(protocolId);
    returnState.resetCtx(std::move(ctx));
    SCOPE_EXIT {
      if (hasRpcOptions && returnState.header()) {
        auto* rheader = returnState.header();
        if (!rheader->getHeaders().empty()) {
          rpcOptions->setReadHeaders(rheader->releaseHeaders());
        }
        rpcOptions->setRoutingData(rheader->releaseRoutingData());
      }
    };
    auto ew = recv_wrapped_put(returnState);
    if (returnState.ctx()) {
      auto tryObj = returnState.ctx()->processClientInterceptorsOnResponse(returnState.header(), ew);
      if (tryObj.hasException()) {
        ew = std::move(tryObj.exception());
      }
    }
    if (ew) {
      co_yield folly::coro::co_error(std::move(ew));
    }
  }
 public:
#endif // FOLLY_HAS_COROUTINES

  /** Glean {"file": "if/KeyValue.thrift", "service": "KeyValueStore", "function": "put"} */
  virtual void put(folly::Function<void (::apache::thrift::ClientReceiveState&&)> callback, const ::kv::PutRequest& p_req);


  /** Glean {"file": "if/KeyValue.thrift", "service": "KeyValueStore", "function": "put"} */
  static folly::exception_wrapper recv_wrapped_put(::apache::thrift::ClientReceiveState& state);
  /** Glean {"file": "if/KeyValue.thrift", "service": "KeyValueStore", "function": "put"} */
  static void recv_put(::apache::thrift::ClientReceiveState& state);
  // Mock friendly virtual instance method
  /** Glean {"file": "if/KeyValue.thrift", "service": "KeyValueStore", "function": "put"} */
  virtual void recv_instance_put(::apache::thrift::ClientReceiveState& state);
  /** Glean {"file": "if/KeyValue.thrift", "service": "KeyValueStore", "function": "put"} */
  virtual folly::exception_wrapper recv_instance_wrapped_put(::apache::thrift::ClientReceiveState& state);
 private:
  apache::thrift::SerializedRequest fbthrift_serialize_put(const RpcOptions& rpcOptions, apache::thrift::transport::THeader& header, apache::thrift::ContextStack* contextStack, const ::kv::PutRequest& p_req);
  template <typename RpcOptions>
  void fbthrift_send_put(apache::thrift::SerializedRequest&& request, RpcOptions&& rpcOptions, std::shared_ptr<apache::thrift::transport::THeader> header, apache::thrift::RequestClientCallback::Ptr callback, std::unique_ptr<folly::IOBuf> interceptorFrameworkMetadata);
  std::pair<::apache::thrift::ContextStack::UniquePtr, std::shared_ptr<::apache::thrift::transport::THeader>> putCtx(apache::thrift::RpcOptions* rpcOptions);
  template <typename CallbackType>
  folly::SemiFuture<folly::Unit> fbthrift_semifuture_put(apache::thrift::RpcOptions& rpcOptions, const ::kv::PutRequest& p_req);
 public:
  /** Glean {"file": "if/KeyValue.thrift", "service": "KeyValueStore", "function": "get"} */
  virtual void get(std::unique_ptr<apache::thrift::RequestCallback> callback, const ::std::string& p_key);
  /** Glean {"file": "if/KeyValue.thrift", "service": "KeyValueStore", "function": "get"} */
  virtual void get(apache::thrift::RpcOptions& rpcOptions, std::unique_ptr<apache::thrift::RequestCallback> callback, const ::std::string& p_key);
 protected:
  void fbthrift_serialize_and_send_get(apache::thrift::RpcOptions& rpcOptions, std::shared_ptr<apache::thrift::transport::THeader> header, apache::thrift::ContextStack* contextStack, apache::thrift::RequestClientCallback::Ptr callback, const ::std::string& p_key, bool stealRpcOptions = false);
 public:

  /** Glean {"file": "if/KeyValue.thrift", "service": "KeyValueStore", "function": "get"} */
  virtual void sync_get(::kv::GetResponse& _return, const ::std::string& p_key);
  /** Glean {"file": "if/KeyValue.thrift", "service": "KeyValueStore", "function": "get"} */
  virtual void sync_get(apache::thrift::RpcOptions& rpcOptions, ::kv::GetResponse& _return, const ::std::string& p_key);

  /** Glean {"file": "if/KeyValue.thrift", "service": "KeyValueStore", "function": "get"} */
  virtual folly::Future<::kv::GetResponse> future_get(const ::std::string& p_key);
  /** Glean {"file": "if/KeyValue.thrift", "service": "KeyValueStore", "function": "get"} */
  virtual folly::SemiFuture<::kv::GetResponse> semifuture_get(const ::std::string& p_key);
  /** Glean {"file": "if/KeyValue.thrift", "service": "KeyValueStore", "function": "get"} */
  virtual folly::Future<::kv::GetResponse> future_get(apache::thrift::RpcOptions& rpcOptions, const ::std::string& p_key);
  /** Glean {"file": "if/KeyValue.thrift", "service": "KeyValueStore", "function": "get"} */
  virtual folly::SemiFuture<::kv::GetResponse> semifuture_get(apache::thrift::RpcOptions& rpcOptions, const ::std::string& p_key);

#if FOLLY_HAS_COROUTINES
  /** Glean {"file": "if/KeyValue.thrift", "service": "KeyValueStore", "function": "get"} */
  template <int = 0>
  folly::coro::Task<::kv::GetResponse> co_get(const ::std::string& p_key) {
    return co_get<false>(nullptr, p_key);
  }
  /** Glean {"file": "if/KeyValue.thrift", "service": "KeyValueStore", "function": "get"} */
  template <int = 0>
  folly::coro::Task<::kv::GetResponse> co_get(apache::thrift::RpcOptions& rpcOptions, const ::std::string& p_key) {
    return co_get<true>(&rpcOptions, p_key);
  }
 private:
  template <bool hasRpcOptions>
  folly::coro::Task<::kv::GetResponse> co_get(apache::thrift::RpcOptions* rpcOptions, const ::std::string& p_key) {
    const folly::CancellationToken& cancelToken =
        co_await folly::coro::co_current_cancellation_token;
    const bool cancellable = cancelToken.canBeCancelled();
    apache::thrift::ClientReceiveState returnState;
    apache::thrift::ClientCoroCallback<false> callback(&returnState, co_await folly::coro::co_current_executor);
    auto protocolId = apache::thrift::GeneratedAsyncClient::getChannel()->getProtocolId();
    auto [ctx, header] = getCtx(rpcOptions);
    using CancellableCallback = apache::thrift::CancellableRequestClientCallback<false>;
    auto cancellableCallback = cancellable ? CancellableCallback::create(&callback, channel_) : nullptr;
    static apache::thrift::RpcOptions* defaultRpcOptions = new apache::thrift::RpcOptions();
    auto wrappedCallback = apache::thrift::RequestClientCallback::Ptr(cancellableCallback ? (apache::thrift::RequestClientCallback*)cancellableCallback.get() : &callback);
    if (ctx != nullptr) {
      auto argsAsRefs = std::tie(p_key);
      auto interceptorTry = ctx->processClientInterceptorsOnRequest(apache::thrift::ClientInterceptorOnRequestArguments(argsAsRefs), header.get(), hasRpcOptions ? *rpcOptions : *defaultRpcOptions);
      if (interceptorTry.hasException()) {
        co_yield folly::coro::co_error(std::move(interceptorTry.exception()));
      }
    }
    if constexpr (hasRpcOptions) {
      fbthrift_serialize_and_send_get(*rpcOptions, header, ctx.get(), std::move(wrappedCallback), p_key);
    } else {
      fbthrift_serialize_and_send_get(*defaultRpcOptions, header, ctx.get(), std::move(wrappedCallback), p_key);
    }
    if (cancellable) {
      folly::CancellationCallback cb(cancelToken, [&] { CancellableCallback::cancel(std::move(cancellableCallback)); });
      co_await callback.co_waitUntilDone();
    } else {
      co_await callback.co_waitUntilDone();
    }
    if (returnState.isException()) {
      co_yield folly::coro::co_error(std::move(returnState.exception()));
    }
    returnState.resetProtocolId(protocolId);
    returnState.resetCtx(std::move(ctx));
    ::kv::GetResponse _return;
    SCOPE_EXIT {
      if (hasRpcOptions && returnState.header()) {
        auto* rheader = returnState.header();
        if (!rheader->getHeaders().empty()) {
          rpcOptions->setReadHeaders(rheader->releaseHeaders());
        }
        rpcOptions->setRoutingData(rheader->releaseRoutingData());
      }
    };
    auto ew = recv_wrapped_get(_return, returnState);
    if (returnState.ctx()) {
      returnState.ctx()->processClientInterceptorsOnResponse(returnState.header(), ew, _return).throwUnlessValue();
    }
    if (ew) {
      co_yield folly::coro::co_error(std::move(ew));
    }
    co_return _return;
  }
 public:
#endif // FOLLY_HAS_COROUTINES

  /** Glean {"file": "if/KeyValue.thrift", "service": "KeyValueStore", "function": "get"} */
  virtual void get(folly::Function<void (::apache::thrift::ClientReceiveState&&)> callback, const ::std::string& p_key);


  /** Glean {"file": "if/KeyValue.thrift", "service": "KeyValueStore", "function": "get"} */
  static folly::exception_wrapper recv_wrapped_get(::kv::GetResponse& _return, ::apache::thrift::ClientReceiveState& state);
  /** Glean {"file": "if/KeyValue.thrift", "service": "KeyValueStore", "function": "get"} */
  static void recv_get(::kv::GetResponse& _return, ::apache::thrift::ClientReceiveState& state);
  // Mock friendly virtual instance method
  /** Glean {"file": "if/KeyValue.thrift", "service": "KeyValueStore", "function": "get"} */
  virtual void recv_instance_get(::kv::GetResponse& _return, ::apache::thrift::ClientReceiveState& state);
  /** Glean {"file": "if/KeyValue.thrift", "service": "KeyValueStore", "function": "get"} */
  virtual folly::exception_wrapper recv_instance_wrapped_get(::kv::GetResponse& _return, ::apache::thrift::ClientReceiveState& state);
 private:
  apache::thrift::SerializedRequest fbthrift_serialize_get(const RpcOptions& rpcOptions, apache::thrift::transport::THeader& header, apache::thrift::ContextStack* contextStack, const ::std::string& p_key);
  template <typename RpcOptions>
  void fbthrift_send_get(apache::thrift::SerializedRequest&& request, RpcOptions&& rpcOptions, std::shared_ptr<apache::thrift::transport::THeader> header, apache::thrift::RequestClientCallback::Ptr callback, std::unique_ptr<folly::IOBuf> interceptorFrameworkMetadata);
  std::pair<::apache::thrift::ContextStack::UniquePtr, std::shared_ptr<::apache::thrift::transport::THeader>> getCtx(apache::thrift::RpcOptions* rpcOptions);
  template <typename CallbackType>
  folly::SemiFuture<::kv::GetResponse> fbthrift_semifuture_get(apache::thrift::RpcOptions& rpcOptions, const ::std::string& p_key);
 public:
};

} // namespace apache::thrift

namespace kv {
using KeyValueStoreAsyncClient [[deprecated("Use apache::thrift::Client<KeyValueStore> instead")]] = ::apache::thrift::Client<KeyValueStore>;
} // namespace kv
