/**
 * Autogenerated by Thrift for if/KeyValue.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */

#include "if/gen-cpp2/KeyValueStore.h"
#include "if/gen-cpp2/KeyValueStore.tcc"

namespace kv {
} // namespace kv
