/**
 * Autogenerated by Thrift for if/KeyValue.thrift
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated @nocommit
 */

#include "if/gen-cpp2/KeyValue_constants.h"

#include <thrift/lib/cpp2/gen/module_constants_cpp.h>


namespace kv {
namespace KeyValue_constants {


::std::string_view _fbthrift_schema_576b3dc35ad691a2() {
  return "";
}
::folly::Range<const ::std::string_view*> _fbthrift_schema_576b3dc35ad691a2_includes() {
  return {};
}
::folly::Range<const ::std::string_view*> _fbthrift_schema_576b3dc35ad691a2_uris() {
  return {};
}

} // namespace KeyValue_constants
} // namespace kv
